#!/usr/bin/env python3

total = 0
x = int(input())
total = total + ((x % 2) * x)
x = int(input())
total = total + ((x % 2) * x)
x = int(input())
total = total + ((x % 2) * x)
x = int(input())
total = total + ((x % 2) * x)
x = int(input())
total = total + ((x % 2) * x)
x = int(input())
total = total + ((x % 2) * x)
x = int(input())
total = total + ((x % 2) * x)
x = int(input())
total = total + ((x % 2) * x)
x = int(input())
total = total + ((x % 2) * x)
x = int(input())
total = total + ((x % 2) * x)
print(total)
